import supertest from 'supertest'
import createTestDatabase from '@tests/utils/createTestDatabase'
import {createFor} from '@tests/utils/records'
import {omit} from 'lodash/fp'
import {fakeEmoji, emojiMatcher} from './utils'
import createApp from '@/app'

const db = await createTestDatabase()
const app = createApp(db)

// builds helper function to create emojis
const createEmojis = createFor(db, 'emoji')

afterEach(async () => {
  // clearing the tested table after each test
  await db.deleteFrom('emoji').execute()
})

// close the database connection after all tests
// For SQLite, this is not necessary, but for other databases, it is.
afterAll(() => db.destroy())

// This is not called "contoller.spec.ts" because we are specifying what this
// entire module should do, not just the controller.

// This could be moved to root-level tests folder, however, nearly always
// breaking tests here means issues in the emojis module, so we are colocating
// it with the module.
describe('GET', () => {
  it('should return an empty array when there are no emojis', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app).get('/emojis').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual([])
  })

  it('should return a list of existing emojis', async () => {
    // ARRANGE (Given that we have...)
    await createEmojis([
      // we have a function that spits out a generic fake emoji
      fakeEmoji(),

      // we generate a slightly different emoji
      // in this function call we provide what should
      // be different from the our default generic emoji
      fakeEmoji({
        emojiStr: '🥳🥳🥳'
      })
    ])

    // ACT (When we request...)
    const {body} = await supertest(app).get('/emojis').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual([
      emojiMatcher(),
      emojiMatcher({
        emojiStr: '🥳🥳🥳'
      })
    ])

    // This is same as:
    // expect(body).toEqual([
    //   {
    //     id: expect.any(Number), // we do not care about the exact id
    //     title: 'My Title', // our default title, content generated by fakeEmoji
    //     content: 'Some Content',
    //   },
    //   {
    //     id: expect.any(Number),
    //     title: 'Title 2', // our custom title
    //     content: 'Other Content',
    //   },
    // ]);
  })
})

describe('GET /:id', () => {
  it('should return 404 if emoji does not exist', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app).get('/emojis/2912').expect(404)

    // ASSERT (Then we should get...)
    // Some error message that contains "not found".
    // Instead of stating the exact error message, we use a
    // regular expression to draw slightly more flexible boundaries
    // around our expectations. If we wanted to slightly change
    // our error message in code, we would not want these tests to break,
    // as long as the error message still contains "not found" in some
    // form: "EmojiNotFound", "Not found", "Emoji was not found"...
    expect(body.error.message).toMatch(/not found/i)
  })

  it('should return an emoji if it exists', async () => {
    // ARRANGE (Given that we have...)
    await createEmojis([
      fakeEmoji({
        id: 1371
      })
    ])

    // ACT (When we request...)
    const {body} = await supertest(app).get('/emojis/1371').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual(
      emojiMatcher({
        id: 1371
      })
    )
  })
})

describe('POST', () => {
  it('should return 400 if emojiStr is missing', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app)
      .post('/emojis')
      .send(omit(['emojiStr'], fakeEmoji({})))
      .expect(400)

    // ASSERT (Then we should get...)
    expect(body.error.message).toMatch(/emojiStr/i)
  })

  it('does not allow to create a emoji with empty emojiStr', async () => {
    const {body} = await supertest(app)
      .post('/emojis')
      .send(fakeEmoji({emojiStr: ''}))
      .expect(400)

    expect(body.error.message).toMatch(/emojiStr/i)
  })

  it('should return 201 and created emoji record', async () => {
    const {body} = await supertest(app)
      .post('/emojis')
      .send(
        fakeEmoji({
          emojiStr: '🥳'
        })
      )
      .expect(201)

    expect(body).toEqual(emojiMatcher())
  })
})

describe('PATCH /:id', () => {
  it('returns 404 if emoji does not exist', async () => {
    const {body} = await supertest(app)
      .patch('/emojis/123456')
      .send(fakeEmoji())
      .expect(404)

    expect(body.error.message).toMatch(/not found/i)
  })

  it('allows partial updates', async () => {
    const id = 137234
    await createEmojis([
      fakeEmoji({
        id
      })
    ])

    const {body} = await supertest(app)
      .patch(`/emojis/${137234}`)
      .send({
        emojiStr: '🥳'
      })
      .expect(200)

    expect(body).toEqual(
      emojiMatcher({
        id,
        emojiStr: '🥳'
      })
    )
  })

  it('persists changes', async () => {
    const id = 41512
    await createEmojis([fakeEmoji({id})])

    await supertest(app)
      .patch(`/emojis/${id}`)
      .send({
        emojiStr: '🥳'
      })
      .expect(200)

    const {body} = await supertest(app).get('/emojis/41512').expect(200)

    expect(body).toEqual(
      emojiMatcher({
        emojiStr: '🥳'
      })
    )
  })
})

describe('DELETE', () => {
  it('returns 404 if emoji does not exist', async () => {
    const {body} = await supertest(app).delete('/emojis/123456').expect(404)

    expect(body.error.message).toMatch(/not found/i)
  })

  it('returns 200 on successfull deletion', async () => {
    const id = 123
    await createEmojis([fakeEmoji({id})])

    await supertest(app).delete('/emojis/123').expect(204)
  })

  it('returns no body content on success', async () => {
    const id = 123
    await createEmojis([fakeEmoji({id})])

    const record = await supertest(app).delete('/emojis/123')
    expect(record.body).toEqual({})
  })
})
