import supertest from 'supertest'
import createTestDatabase from '@tests/utils/createTestDatabase'
import {createFor} from '@tests/utils/records'
import {omit} from 'lodash/fp'
import {fakeTemplate, templateMatcher} from './utils'
import createApp from '@/app'

const db = await createTestDatabase()
const app = createApp(db)

// builds helper function to create templates
const createTemplates = createFor(db, 'template')

afterEach(async () => {
  // clearing the tested table after each test
  await db.deleteFrom('template').execute()
})

// close the database connection after all tests
// For SQLite, this is not necessary, but for other databases, it is.
afterAll(() => db.destroy())

// This is not called "contoller.spec.ts" because we are specifying what this
// entire module should do, not just the controller.

// This could be moved to root-level tests folder, however, nearly always
// breaking tests here means issues in the templates module, so we are colocating
// it with the module.
describe('GET', () => {
  it('should return an empty array when there are no templates', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app).get('/templates').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual([])
  })

  it('should return a list of existing templates', async () => {
    // ARRANGE (Given that we have...)
    await createTemplates([
      // we have a function that spits out a generic fake template
      fakeTemplate(),

      // we generate a slightly different template
      // in this function call we provide what should
      // be different from the our default generic template
      fakeTemplate({
        templateStr: 'You did really well 1!'
      })
    ])

    // ACT (When we request...)
    const {body} = await supertest(app).get('/templates').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual([
      templateMatcher(),
      templateMatcher({
        templateStr: 'You did really well 1!'
      })
    ])

    // This is same as:
    // expect(body).toEqual([
    //   {
    //     id: expect.any(Number), // we do not care about the exact id
    //     title: 'My Title', // our default title, content generated by fakeTemplate
    //     content: 'Some Content',
    //   },
    //   {
    //     id: expect.any(Number),
    //     title: 'Title 2', // our custom title
    //     content: 'Other Content',
    //   },
    // ]);
  })
})

describe('GET /:id', () => {
  it('should return 404 if template does not exist', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app).get('/templates/2912').expect(404)

    // ASSERT (Then we should get...)
    // Some error message that contains "not found".
    // Instead of stating the exact error message, we use a
    // regular expression to draw slightly more flexible boundaries
    // around our expectations. If we wanted to slightly change
    // our error message in code, we would not want these tests to break,
    // as long as the error message still contains "not found" in some
    // form: "TemplateNotFound", "Not found", "Template was not found"...
    expect(body.error.message).toMatch(/not found/i)
  })

  it('should return an template if it exists', async () => {
    // ARRANGE (Given that we have...)
    await createTemplates([
      fakeTemplate({
        id: 1371
      })
    ])

    // ACT (When we request...)
    const {body} = await supertest(app).get('/templates/1371').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual(
      templateMatcher({
        id: 1371
      })
    )
  })
})

describe('POST', () => {
  it('should return 400 if templateStr is missing', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app)
      .post('/templates')
      .send(omit(['templateStr'], fakeTemplate({})))
      .expect(400)

    // ASSERT (Then we should get...)
    expect(body.error.message).toMatch(/templateStr/i)
  })

  it('does not allow to create a template with empty templateStr', async () => {
    const {body} = await supertest(app)
      .post('/templates')
      .send(fakeTemplate({templateStr: ''}))
      .expect(400)

    expect(body.error.message).toMatch(/templateStr/i)
  })

  it('should return 201 and created template record', async () => {
    const {body} = await supertest(app)
      .post('/templates')
      .send(fakeTemplate())
      .expect(201)

    expect(body).toEqual(templateMatcher())
  })
})

describe('PATCH /:id', () => {
  it('returns 404 if template does not exist', async () => {
    const {body} = await supertest(app)
      .patch('/templates/123456')
      .send(fakeTemplate())
      .expect(404)

    expect(body.error.message).toMatch(/not found/i)
  })

  it('allows partial updates', async () => {
    const id = 137234
    await createTemplates([
      fakeTemplate({
        id
      })
    ])

    const {body} = await supertest(app)
      .patch(`/templates/${137234}`)
      .send({templateStr: 'Job well done!'})
      .expect(200)

    expect(body).toEqual(
      templateMatcher({
        id,
        templateStr: 'Job well done!'
      })
    )
  })

  it('persists changes', async () => {
    const id = 41512
    await createTemplates([fakeTemplate({id})])

    await supertest(app)
      .patch(`/templates/${id}`)
      .send({templateStr: 'Job well done!'})
      .expect(200)

    const {body} = await supertest(app).get('/templates/41512').expect(200)

    expect(body).toEqual(
      templateMatcher({
        templateStr: 'Job well done!'
      })
    )
  })
})

describe('DELETE', () => {
  it('returns 404 if template does not exist', async () => {
    const {body} = await supertest(app).delete('/templates/123456').expect(404)

    expect(body.error.message).toMatch(/not found/i)
  })

  it('returns 200 on successfull deletion', async () => {
    const id = 123
    await createTemplates([fakeTemplate({id})])

    await supertest(app).delete('/templates/123').expect(204)
  })

  it('returns no body content on success', async () => {
    const id = 123
    await createTemplates([fakeTemplate({id})])

    const record = await supertest(app).delete('/templates/123')
    expect(record.body).toEqual({})
  })
})
