import supertest from 'supertest'
import createTestDatabase from '@tests/utils/createTestDatabase'
import {createFor} from '@tests/utils/records'
import {omit} from 'lodash/fp'
import {fakeUser, userMatcher} from './utils'
import createApp from '@/app'

const db = await createTestDatabase()
const app = createApp(db)

// builds helper function to create users
const createUsers = createFor(db, 'user')

afterEach(async () => {
  // clearing the tested table after each test
  await db.deleteFrom('user').execute()
})

// close the database connection after all tests
// For SQLite, this is not necessary, but for other databases, it is.
afterAll(() => db.destroy())

// This is not called "contoller.spec.ts" because we are specifying what this
// entire module should do, not just the controller.

// This could be moved to root-level tests folder, however, nearly always
// breaking tests here means issues in the users module, so we are colocating
// it with the module.
describe('GET', () => {
  it('should return an empty array when there are no users', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app).get('/users').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual([])
  })

  it('should return a list of existing users', async () => {
    // ARRANGE (Given that we have...)
    await createUsers([
      // we have a function that spits out a generic fake user
      fakeUser(),

      // we generate a slightly different user
      // in this function call we provide what should
      // be different from the our default generic user
      fakeUser({
        username: 'augriga'
      })
    ])

    // ACT (When we request...)
    const {body} = await supertest(app).get('/users').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual([
      userMatcher(),
      userMatcher({
        username: 'augriga'
      })
    ])

    // This is same as:
    // expect(body).toEqual([
    //   {
    //     id: expect.any(Number), // we do not care about the exact id
    //     title: 'My Title', // our default title, content generated by fakeUser
    //     content: 'Some Content',
    //   },
    //   {
    //     id: expect.any(Number),
    //     title: 'Title 2', // our custom title
    //     content: 'Other Content',
    //   },
    // ]);
  })
})

describe('GET /:id', () => {
  it('should return 404 if user does not exist', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app).get('/users/2912').expect(404)

    // ASSERT (Then we should get...)
    // Some error message that contains "not found".
    // Instead of stating the exact error message, we use a
    // regular expression to draw slightly more flexible boundaries
    // around our expectations. If we wanted to slightly change
    // our error message in code, we would not want these tests to break,
    // as long as the error message still contains "not found" in some
    // form: "UserNotFound", "Not found", "User was not found"...
    expect(body.error.message).toMatch(/not found/i)
  })

  it('should return an user if it exists', async () => {
    // ARRANGE (Given that we have...)
    await createUsers([
      fakeUser({
        id: 1371
      })
    ])

    // ACT (When we request...)
    const {body} = await supertest(app).get('/users/1371').expect(200)

    // ASSERT (Then we should get...)
    expect(body).toEqual(
      userMatcher({
        id: 1371
      })
    )
  })
})

describe('POST', () => {
  it('should return 400 if username is missing', async () => {
    // ACT (When we request...)
    const {body} = await supertest(app)
      .post('/users')
      .send(omit(['username'], fakeUser({})))
      .expect(400)

    // ASSERT (Then we should get...)
    expect(body.error.message).toMatch(/username/i)
  })

  it('does not allow to create a user with empty username', async () => {
    const {body} = await supertest(app)
      .post('/users')
      .send(fakeUser({username: ''}))
      .expect(400)

    expect(body.error.message).toMatch(/username/i)
  })

  it('should return 201 and created user record', async () => {
    const {body} = await supertest(app)
      .post('/users')
      .send(fakeUser())
      .expect(201)

    expect(body).toEqual(userMatcher())
  })
})

describe('PATCH /:id', () => {
  it('returns 404 if user does not exist', async () => {
    const {body} = await supertest(app)
      .patch('/users/123456')
      .send(fakeUser())
      .expect(404)

    expect(body.error.message).toMatch(/not found/i)
  })

  it('allows partial updates', async () => {
    const id = 137234
    await createUsers([
      fakeUser({
        id
      })
    ])

    const {body} = await supertest(app)
      .patch(`/users/${137234}`)
      .send({username: 'vjuodz'})
      .expect(200)

    expect(body).toEqual(
      userMatcher({
        id,
        username: 'vjuodz'
      })
    )
  })

  it('persists changes', async () => {
    const id = 41512
    await createUsers([fakeUser({id})])

    await supertest(app)
      .patch(`/users/${id}`)
      .send({username: 'vjuodz'})
      .expect(200)

    const {body} = await supertest(app).get('/users/41512').expect(200)

    expect(body).toEqual(
      userMatcher({
        username: 'vjuodz'
      })
    )
  })
})

describe('DELETE', () => {
  it('returns 404 if user does not exist', async () => {
    const {body} = await supertest(app).delete('/users/123456').expect(404)

    expect(body.error.message).toMatch(/not found/i)
  })

  it('returns 204 on successfull deletion', async () => {
    const id = 123
    await createUsers([fakeUser({id})])

    await supertest(app).delete('/users/123').expect(204)
  })

  it('returns no body content on success', async () => {
    const id = 123
    await createUsers([fakeUser({id})])

    const record = await supertest(app).delete('/users/123')
    expect(record.body).toEqual({})
  })
})
