# Simple workflow for deploying static content to GitHub Pages
name: Lint & Test

on:
  pull_request:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build
        run: npm run build
