# Simple workflow for deploying static content to GitHub Pages
name: Lint & Test

on:
  pull_request:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run coverage
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          PORT: ${{ vars.PORT }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage/*.json
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
